import React, { useState, useCallback, useMemo, useEffect } from 'react';
import { Link } from 'react-router-dom';
import axios from 'axios';
import { useWatchlist } from '../hooks/useWatchlist';
import MovieCard from '../components/MovieCard';

const apiKey = process.env.REACT_APP_TMDB_API_KEY || 'f2b1a353af51ccd27736c209f7ea0ca6';

/**
 * Watchlist page with export, notes, random picker, matchmaker, and personalized recs
 */
function Watchlist() {
    const { watchlist, toggleWatchlist, isInWatchlist, getNote, setNote, getRandomMovie } = useWatchlist();
    const [exportStatus, setExportStatus] = useState('');
    const [randomPick, setRandomPick] = useState(null);
    const [showMatchmaker, setShowMatchmaker] = useState(false);
    const [matchInput, setMatchInput] = useState('');
    const [matchResults, setMatchResults] = useState(null);
    const [editingNote, setEditingNote] = useState(null);
    const [noteText, setNoteText] = useState('');
    const [personalizedRecs, setPersonalizedRecs] = useState([]);
    const [recsLoading, setRecsLoading] = useState(false);
    const [recsBasedOn, setRecsBasedOn] = useState(null);

    // Sort by most recently added
    const sortedWatchlist = useMemo(() =>
        [...watchlist].sort((a, b) => b.addedAt - a.addedAt),
        [watchlist]
    );

    // Export watchlist to clipboard
    const handleExport = useCallback(async () => {
        if (sortedWatchlist.length === 0) return;

        const exportText = sortedWatchlist.map(item => {
            const year = item.release_date
                ? ` (${new Date(item.release_date).getFullYear()})`
                : '';
            const type = item.media_type === 'tv' ? ' [TV]' : '';
            return `• ${item.title}${year}${type}`;
        }).join('\n');

        const fullExport = `🎬 My MoodReel Watchlist\n${'─'.repeat(25)}\n${exportText}\n\nGenerated by MoodReel`;

        try {
            await navigator.clipboard.writeText(fullExport);
            setExportStatus('Copied!');
            setTimeout(() => setExportStatus(''), 3000);
        } catch (err) {
            const textarea = document.createElement('textarea');
            textarea.value = fullExport;
            document.body.appendChild(textarea);
            textarea.select();
            document.execCommand('copy');
            document.body.removeChild(textarea);
            setExportStatus('Copied!');
            setTimeout(() => setExportStatus(''), 3000);
        }
    }, [sortedWatchlist]);

    // Random picker
    const handleRandomPick = useCallback(() => {
        const movie = getRandomMovie();
        setRandomPick(movie);
        // Clear after 10 seconds
        setTimeout(() => setRandomPick(null), 10000);
    }, [getRandomMovie]);

    // Matchmaker - find movies that appear in pasted friend's list
    const handleMatch = useCallback(() => {
        const friendTitles = matchInput
            .split('\n')
            .map(line => line.replace(/^[•\-*]\s*/, '').split('(')[0].trim().toLowerCase())
            .filter(Boolean);

        const matches = sortedWatchlist.filter(movie =>
            friendTitles.some(title =>
                movie.title.toLowerCase().includes(title) ||
                title.includes(movie.title.toLowerCase())
            )
        );

        setMatchResults({
            count: matches.length,
            movies: matches
        });
    }, [matchInput, sortedWatchlist]);

    // Notes editing
    const startEditNote = useCallback((movieId) => {
        setEditingNote(movieId);
        setNoteText(getNote(movieId));
    }, [getNote]);

    const saveNote = useCallback(() => {
        if (editingNote) {
            setNote(editingNote, noteText);
            setEditingNote(null);
            setNoteText('');
        }
    }, [editingNote, noteText, setNote]);

    // Fetch personalized recommendations
    const fetchPersonalizedRecs = useCallback(async () => {
        if (watchlist.length === 0) return;

        setRecsLoading(true);
        const randomMovie = watchlist[Math.floor(Math.random() * watchlist.length)];
        setRecsBasedOn(randomMovie);

        try {
            const mediaType = randomMovie.media_type || 'movie';
            const response = await axios.get(
                `https://api.themoviedb.org/3/${mediaType}/${randomMovie.id}/similar?api_key=${apiKey}`
            );

            // Filter out movies already in watchlist
            const filtered = response.data.results
                .filter(m => !watchlist.some(w => w.id === m.id))
                .slice(0, 4)
                .map(m => ({ ...m, media_type: mediaType }));

            setPersonalizedRecs(filtered);
        } catch (err) {
            console.error('Error fetching recommendations:', err);
            setPersonalizedRecs([]);
        } finally {
            setRecsLoading(false);
        }
    }, [watchlist]);

    // Load personalized recs on mount if watchlist has items
    useEffect(() => {
        if (watchlist.length >= 3 && personalizedRecs.length === 0) {
            fetchPersonalizedRecs();
        }
    }, [watchlist.length, personalizedRecs.length, fetchPersonalizedRecs]);

    return (
        <div className="watchlist-page">
            <div className="watchlist-header">
                <h2>My Watchlist</h2>
                <div className="watchlist-actions">
                    {sortedWatchlist.length > 1 && (
                        <button className="action-btn" onClick={handleRandomPick} title="Pick random movie">
                            🎲 Pick for Me
                        </button>
                    )}
                    {sortedWatchlist.length > 0 && (
                        <>
                            <button className="action-btn" onClick={() => setShowMatchmaker(!showMatchmaker)}>
                                👥 Matchmaker
                            </button>
                            <button className="export-btn" onClick={handleExport}>
                                {exportStatus || '📋 Export'}
                            </button>
                        </>
                    )}
                </div>
            </div>

            {/* Personalized Recommendations */}
            {watchlist.length >= 3 && (
                <div className="personalized-recs">
                    <div className="recs-header">
                        <h3>
                            {recsBasedOn ? (
                                <>✨ Because you saved <em>{recsBasedOn.title}</em></>)
                                : (
                                    <>✨ Recommended for you</>)
                            }
                        </h3>
                        <button
                            className="refresh-recs-btn"
                            onClick={fetchPersonalizedRecs}
                            disabled={recsLoading}
                        >
                            {recsLoading ? '...' : '🔄 Refresh'}
                        </button>
                    </div>
                    {personalizedRecs.length > 0 ? (
                        <div className="recs-grid">
                            {personalizedRecs.map(movie => (
                                <MovieCard
                                    key={movie.id}
                                    movie={movie}
                                    isInWatchlist={isInWatchlist(movie.id)}
                                    onToggleWatchlist={toggleWatchlist}
                                    mediaType={movie.media_type}
                                />
                            ))}
                        </div>
                    ) : (
                        <p className="recs-empty">Loading recommendations...</p>
                    )}
                </div>
            )}

            {/* Random Pick Result */}
            {randomPick && (
                <div className="random-pick-banner">
                    <span className="pick-icon">🎲</span>
                    <div className="pick-content">
                        <p>Tonight's pick:</p>
                        <h3>{randomPick.title}</h3>
                    </div>
                    <Link to={`/${randomPick.media_type}/${randomPick.id}`} className="view-pick-btn">
                        View Details →
                    </Link>
                </div>
            )}

            {/* Matchmaker Panel */}
            {showMatchmaker && (
                <div className="matchmaker-panel">
                    <h4>👥 Movie Matchmaker</h4>
                    <p>Paste a friend's exported watchlist to find movies you both want to watch!</p>
                    <textarea
                        value={matchInput}
                        onChange={(e) => setMatchInput(e.target.value)}
                        placeholder="Paste friend's watchlist here..."
                        rows={4}
                    />
                    <button onClick={handleMatch} className="primary-button">
                        Find Matches
                    </button>

                    {matchResults && (
                        <div className="match-results">
                            {matchResults.count > 0 ? (
                                <>
                                    <p className="match-success">
                                        🎉 Found {matchResults.count} movie{matchResults.count > 1 ? 's' : ''} in common!
                                    </p>
                                    <div className="match-list">
                                        {matchResults.movies.map(m => (
                                            <span key={m.id} className="match-chip">{m.title}</span>
                                        ))}
                                    </div>
                                </>
                            ) : (
                                <p className="no-matches">No matches found. You have unique taste! 🎬</p>
                            )}
                        </div>
                    )}
                </div>
            )}

            {sortedWatchlist.length === 0 ? (
                <div className="empty-state">
                    <div className="icon">🎬</div>
                    <h3>Your watchlist is empty</h3>
                    <p>Start adding movies and shows you want to watch!</p>
                    <Link to="/" className="primary-button">
                        Discover Movies
                    </Link>
                </div>
            ) : (
                <>
                    <p className="watchlist-count">
                        {sortedWatchlist.length} {sortedWatchlist.length === 1 ? 'item' : 'items'} saved
                    </p>
                    <div className="watchlist-grid">
                        {sortedWatchlist.map((item) => {
                            const note = getNote(item.id);
                            return (
                                <div key={item.id} className="watchlist-item">
                                    <MovieCard
                                        movie={item}
                                        isInWatchlist={isInWatchlist(item.id)}
                                        onToggleWatchlist={toggleWatchlist}
                                        mediaType={item.media_type}
                                    />

                                    {/* Note section */}
                                    <div className="movie-note">
                                        {editingNote === item.id ? (
                                            <div className="note-editor">
                                                <textarea
                                                    value={noteText}
                                                    onChange={(e) => setNoteText(e.target.value)}
                                                    placeholder="Add a note..."
                                                    rows={2}
                                                />
                                                <div className="note-actions">
                                                    <button onClick={saveNote}>Save</button>
                                                    <button onClick={() => setEditingNote(null)}>Cancel</button>
                                                </div>
                                            </div>
                                        ) : note ? (
                                            <div className="note-display" onClick={() => startEditNote(item.id)}>
                                                📝 {note}
                                            </div>
                                        ) : (
                                            <button
                                                className="add-note-btn"
                                                onClick={() => startEditNote(item.id)}
                                            >
                                                + Add note
                                            </button>
                                        )}
                                    </div>
                                </div>
                            );
                        })}
                    </div>
                </>
            )}

            <Link to="/stats" className="stats-link">
                📊 View Your Stats →
            </Link>
        </div>
    );
}

export default Watchlist;
