import React, { useState, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { useWatchlist } from '../hooks/useWatchlist';
import MovieCard from '../components/MovieCard';

/**
 * Watchlist page showing saved movies with export functionality
 */
function Watchlist() {
    const { watchlist, toggleWatchlist, isInWatchlist } = useWatchlist();
    const [exportStatus, setExportStatus] = useState('');

    // Sort by most recently added
    const sortedWatchlist = [...watchlist].sort((a, b) => b.addedAt - a.addedAt);

    // Export watchlist to clipboard
    const handleExport = useCallback(async () => {
        if (sortedWatchlist.length === 0) return;

        const exportText = sortedWatchlist.map(item => {
            const year = item.release_date
                ? ` (${new Date(item.release_date).getFullYear()})`
                : '';
            const type = item.media_type === 'tv' ? ' [TV]' : '';
            return `• ${item.title}${year}${type}`;
        }).join('\n');

        const fullExport = `🎬 My MoodReel Watchlist\n${'─'.repeat(25)}\n${exportText}\n\nGenerated by MoodReel`;

        try {
            await navigator.clipboard.writeText(fullExport);
            setExportStatus('Copied to clipboard!');
            setTimeout(() => setExportStatus(''), 3000);
        } catch (err) {
            // Fallback for older browsers
            const textarea = document.createElement('textarea');
            textarea.value = fullExport;
            document.body.appendChild(textarea);
            textarea.select();
            document.execCommand('copy');
            document.body.removeChild(textarea);
            setExportStatus('Copied to clipboard!');
            setTimeout(() => setExportStatus(''), 3000);
        }
    }, [sortedWatchlist]);

    return (
        <div className="watchlist-page">
            <div className="watchlist-header">
                <h2>My Watchlist</h2>
                {sortedWatchlist.length > 0 && (
                    <button
                        className="export-btn"
                        onClick={handleExport}
                        title="Export watchlist"
                    >
                        {exportStatus || '📋 Export'}
                    </button>
                )}
            </div>

            {sortedWatchlist.length === 0 ? (
                <div className="empty-state">
                    <div className="icon">🎬</div>
                    <h3>Your watchlist is empty</h3>
                    <p>Start adding movies and shows you want to watch!</p>
                    <Link to="/" className="primary-button">
                        Discover Movies
                    </Link>
                </div>
            ) : (
                <>
                    <p style={{
                        textAlign: 'center',
                        color: 'var(--color-text-secondary)',
                        marginBottom: 'var(--spacing-xl)'
                    }}>
                        {sortedWatchlist.length} {sortedWatchlist.length === 1 ? 'item' : 'items'} saved
                    </p>
                    <div className="recommendations">
                        {sortedWatchlist.map((item) => (
                            <MovieCard
                                key={item.id}
                                movie={item}
                                isInWatchlist={isInWatchlist(item.id)}
                                onToggleWatchlist={toggleWatchlist}
                                mediaType={item.media_type}
                            />
                        ))}
                    </div>
                </>
            )}
        </div>
    );
}

export default Watchlist;
